version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OPENMETEO_URL=${OPENMETEO_URL:-https://api.open-meteo.com/v1/forecast}
      - API_HOST=0.0.0.0
      - API_PORT=8000
    command: python -m uvicorn api.main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  streamlit:
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - OPENMETEO_URL=${OPENMETEO_URL:-https://api.open-meteo.com/v1/forecast}
      - API_HOST=api
      - API_PORT=8000
      # As credenciais são carregadas do arquivo .env
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - MAPS_API_KEY=${MAPS_API_KEY}
    depends_on:
      - api
    command: python -m streamlit run app_streamlit.py --server.port=8501 --server.address=0.0.0.0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge




